
spring:
  security:
    oauth2:
      client:
        registration:
          api-client:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/api-client
            scope: openid
            client-name: api-client
          api-client-authorization-code:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/authorized
            scope: read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9090
